%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(protocol_pb).
-define(protocol_pb, true).

-define(protocol_pb_gpb_version, "3.26.4").

-ifndef('PEOPLE_PB_H').
-define('PEOPLE_PB_H', true).
-record('People',
        {name                   :: binary() | iolist(), % = 1
         id                     :: integer(),       % = 2, 32 bits
         email                  :: binary() | iolist() | undefined % = 3
        }).
-endif.

-ifndef('CHATMSG_PB_H').
-define('CHATMSG_PB_H', true).
-record('ChatMsg',
        {msg                    :: binary() | iolist() % = 1
        }).
-endif.

-ifndef('MSG_PB_H').
-define('MSG_PB_H', true).
-record('Msg',
        {msg                    :: binary() | iolist() % = 1
        }).
-endif.

-ifndef('BASE_PB_H').
-define('BASE_PB_H', true).
-record('Base',
        {id                     :: integer(),       % = 2, 32 bits
         data                   :: binary() | undefined % = 0
        }).
-endif.

-endif.
